---
# roles/elk-docker-kibana/tasks/main.yml

- name: Install dependencies for Docker and pip
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - python3-docker
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker APT repository for Ubuntu jammy
  apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu
      jammy stable
    filename: docker
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Remove existing Kibana container if present
  shell: |
    docker rm -f kibana || true
  args:
    executable: /bin/bash

- name: Run Kibana via Docker CLI
  shell: |
    docker run -d \
      --name kibana \
      --network host \
      -e ELASTICSEARCH_HOSTS='["http://elasticsearch.ru-central1.internal:9200"]' \
      kibana:8.6.2
  args:
    executable: /bin/bash
