all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o ProxyJump=ubuntu@51.250.71.224'

  children:
    elasticsearch:
      hosts:
        elasticsearch.ru-central1.internal: {}

    kibana:
      hosts:
        kibana.ru-central1.internal: {}

    webservers:
      hosts:
        web1.ru-central1.internal: {}
        web2.ru-central1.internal: {}
